<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Query</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="icon" href="img/favicon-16x16.png" type="image/x-icon"/>
    <script defer src="js/navbar.js"></script>
</head>
<body>
<nav class="navbar">
    <div class="brand-title">Query</div>
    <a href="#" class="toggle-button">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
    </a>
    <div class="navbar-links">
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="invoice.php">Invoice</a></li>
            <li><a href="roominvoice.php">Rooms</a></li>
        </ul>
    </div>
</nav>

